name: Import ricette da URLs

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: Messaggio commit
        required: false
        default: Import ricette automatico

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Importa
        run: |
          node script/import-recipes.mjs urls.txt > new_recipes.json
          cat new_recipes.json

      - name: Valida nuovi
        run: |
          node script/validate-recipes.mjs assets/json/recipes-it.json new_recipes.json

      - name: Unisci
        run: |
          node script/merge-recipes.mjs assets/json/recipes-it.json new_recipes.json > merged.json
          mv merged.json assets/json/recipes-it.json

      - name: Commit e push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/json/recipes-it.json
          git commit -m "${{ github.event.inputs.commit_message || 'Import ricette automatico' }}" || echo "Nessuna modifica"
          git push

      - name: Report artifact
        uses: actions/upload-artifact@v4
        with:
          name: new_recipes
          path: new_recipes.json
