name: Importa ricette da URLs

on:
  workflow_dispatch:
    inputs:
      limit:
        description: "Quante ricette importare (default 30)"
        required: false
        default: "30"

jobs:
  import:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version: 20

      # Placeholder: serve solo per far comparire il workflow in Actions
      - name: Ensure urls.txt (fallback)
        run: |
          if [ ! -s urls.txt ]; then
            cat > urls.txt <<'EOF'
https://ricette.giallozafferano.it/Gnocchi-alla-sorrentina.html
https://ricette.giallozafferano.it/Pollo-alla-cacciatora.html
https://ricette.giallozafferano.it/Lasagne-alla-Bolognese.html
https://ricette.giallozafferano.it/Tiramisu.html
https://ricette.giallozafferano.it/Pesto-alla-genovese.html
https://ricette.giallozafferano.it/Minestrone-di-verdure.html
EOF
          fi
          echo "Workflow visibile e pronto."

      - name: Done
        run: echo "Ok"
