name: Importa ricette da URLs

on:
  workflow_dispatch: {}
  schedule:
    - cron: "15 2 * * *"  # ogni giorno 02:15 UTC

permissions:
  contents: write

concurrency:
  group: auto-import
  cancel-in-progress: true

jobs:
  import:
    runs-on: ubuntu-latest
    env:
      YT_API_KEY: ${{ secrets.YT_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Sanity check
        run: |
          node -v
          pwd
          ls -lah
          echo "script/"
          ls -lah script || true
          echo "assets/json/"
          ls -lah assets/json || true
          echo "urls.txt:"
          test -f urls.txt && wc -l urls.txt || echo "manca"
          echo "YT_API_KEY length:"
          if [ -n "${YT_API_KEY:-}" ]; then echo ${#YT_API_KEY}; else echo "0"; fi

      - name: Ensure urls.txt
        run: |
          if [ ! -s urls.txt ]; then
            cat > urls.txt <<'EOF'
https://ricette.giallozafferano.it/Gnocchi-alla-sorrentina.html
https://ricette.giallozafferano.it/Pollo-alla-cacciatora.html
https://ricette.giallozafferano.it/Lasagne-alla-Bolognese.html
https://ricette.giallozafferano.it/Tiramisu.html
https://ricette.giallozafferano.it/Pesto-alla-genovese.html
https://ricette.giallozafferano.it/Minestrone-di-verdure.html
EOF
          fi
          echo "Prime 5 URL:"
          head -n 5 urls.txt

      - name: Crawler GZ
        continue-on-error: true
        run: |
          if [ -f script/crawl-gz.mjs ]; then
            node script/crawl-gz.mjs || true
          else
            echo "crawler assente, salto"
          fi

      - name: Import batch
        run: |
          if [ ! -f script/import-recipes.mjs ]; then
            echo "manca script/import-recipes.mjs"
            exit 1
          fi
          node script/import-recipes.mjs urls.txt 30 > new_recipes.json
          test -s new_recipes.json || echo "[]" > new_recipes.json
          echo "Anteprima new_recipes.json:"
          head -c 600 new_recipes.json || true
          echo
          mkdir -p .cache
          # opzionale: se lo script produce .cache/used_urls.txt, lo useremo dopo

      - name: Validate new
        continue-on-error: true
        run: |
          if [ -f script/validate-recipes.mjs ] && [ -s new_recipes.json ]; then
            node script/validate-recipes.mjs new_recipes.json || true
          else
            echo "validatore assente o file vuoto, salto"
          fi

      - name: Merge dataset
        run: |
          DATA="assets/json/recipes-it.json"
          mkdir -p assets/json
          [ -f "$DATA" ] || echo "[]" > "$DATA"
          if [ ! -s new_recipes.json ]; then
            echo "nessuna nuova ricetta, salto merge"
            exit 0
          fi
          if [ -f script/merge-recipes.mjs ]; then
            node script/merge-recipes.mjs "$DATA" new_recipes.json > "${DATA}.tmp"
            mv "${DATA}.tmp" "$DATA"
          else
            echo "manca script/merge-recipes.mjs"
            exit 1
          fi

      - name: Clean urls.txt
        run: |
          if [ -f .cache/used_urls.txt ]; then
            grep -vxF -f .cache/used_urls.txt urls.txt > urls.txt.tmp || true
            mv urls.txt.tmp urls.txt
          else
            echo "nessuna lista URL usate, mantengo urls.txt invariato"
          fi

      - name: Commit and push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "niente da commitare"
            exit 0
          fi
          COUNT=$(node -e "try{console.log((JSON.parse(require('fs').readFileSync('new_recipes.json','utf8'))||[]).length||0)}catch(e){console.log(0)}")
          git commit -m "Import ricette automatico (+$COUNT)"
          git push

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: new_recipes
          path: new_recipes.json
          if-no-files-found: warn
