name: Import ricette da URLs
on: [workflow_dispatch]

permissions:
  contents: write

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Prepare
        run: |
          # se .cache è un file lo rimuovo, poi creo la cartella
          if [ -f .cache ]; then rm -f .cache; fi
          mkdir -p .cache
          touch .cache/gz-seen.txt
          touch urls.txt
          [ -f assets/json/recipes-it.json ] || echo "[]" > assets/json/recipes-it.json

      - name: Crawl
        run: node script/crawl-gz.mjs || true

      - name: Seed urls if empty
        run: |
          if [ ! -s urls.txt ]; then
            echo "https://ricette.giallozafferano.it/Gnocchi-alla-sorrentina.html" > urls.txt
            echo "https://ricette.giallozafferano.it/Pollo-alla-cacciatora.html" >> urls.txt
            echo "https://ricette.giallozafferano.it/Lasagne-alla-Bolognese.html" >> urls.txt
            echo "https://ricette.giallozafferano.it/Tiramisu.html" >> urls.txt
            echo "https://ricette.giallozafferano.it/Pesto-alla-genovese.html" >> urls.txt
            echo "https://ricette.giallozafferano.it/Minestrone-di-verdure.html" >> urls.txt
          fi

      - name: Import 30
        run: node script/import-recipes.mjs urls.txt 30 > new_recipes.json || true

      - name: Ensure new_recipes.json
        run: |
          [ -s new_recipes.json ] || echo "[]" > new_recipes.json
          cat new_recipes.json

      - name: Validate
        run: node script/validate-recipes.mjs new_recipes.json || true

      - name: Merge
        run: |
          node script/merge-recipes.mjs assets/json/recipes-it.json new_recipes.json > recipes-merged.json || true
          [ -s recipes-merged.json ] && mv recipes-merged.json assets/json/recipes-it.json || true

      - name: Trim urls
        run: |
          if [ -s urls.txt ]; then
            tail -n +31 urls.txt > urls.tmp || true
            mv urls.tmp urls.txt || true
          fi

      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add urls.txt assets/json/recipes-it.json .cache/gz-seen.txt || true
          git commit -m "auto-import" || echo "no changes"
          git push || true
