name: Importa ricette da URLs (FULL)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/import-urls-full.yml"

permissions:
  contents: write

concurrency:
  group: auto-import
  cancel-in-progress: true

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Sanity check
        run: |
          node -v
          pwd
          ls -lah
          echo "cartella script:"
          ls -lah script || true
          echo "assets/json:"
          ls -lah assets/json || true

      - name: Echo
        run: echo "OK"

