name: Importa ricette da URLs (FULL)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/import-urls-full.yml"

permissions:
  contents: write

concurrency:
  group: auto-import
  cancel-in-progress: true

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Sanity check
        shell: bash
        run: |
          set -e
          node -v
          pwd
          ls -lah
          echo "cartella script:"
          ls -lah script || true
          echo "assets/json:"
          ls -lah assets/json || true

      - name: Ensure urls.txt
        shell: bash
        run: |
          set -e
          if [ ! -s urls.txt ]; then
            : > urls.txt
            echo "https://ricette.giallozafferano.it/Gnocchi-alla-sorrentina.html" >> urls.txt
            echo "https://ricette.giallozafferano.it/Pollo-alla-cacciatora.html" >> urls.txt
            echo "https://ricette.giallozafferano.it/Lasagne-alla-Bolognese.html" >> urls.txt
            echo "https://ricette.giallozafferano.it/Tiramisu.html" >> urls.txt
            echo "https://ricette.giallozafferano.it/Pesto-alla-genovese.html" >> urls.txt
            echo "https://ricette.giallozafferano.it/Minestrone-di-verdure.html" >> urls.txt
          fi
          echo "Prime 5 URL:"
          head -n 5 urls.txt || true
          echo "Totale URL:"
          wc -l urls.txt

      - name: Import batch
        shell: bash
        run: |
          set -e
          if [ -f script/import-recipes.mjs ]; then
            echo "Eseguo import…"
            node script/import-recipes.mjs urls.txt 30 > new_recipes.json
            if [ ! -s new_recipes.json ]; then
              echo "[]"> new_recipes.json
            fi
            echo "Anteprima new_recipes.json:"
            head -c 800 new_recipes.json || true
          else
            echo "AVVISO: script/import-recipes.mjs assente. Skip import."
            echo "[]"> new_recipes.json
          fi

      - name: Echo
        run: echo "OK"
