name: Importa ricette da URLs (FULL)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/import-urls-full.yml"

permissions:
  contents: write

concurrency:
  group: auto-import
  cancel-in-progress: true

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Sanity check
        run: |
          node -v
          pwd
          ls -lah
          echo "cartella script:"
          ls -lah script || true
          echo "assets/json:"
          ls -lah assets/json || true

      - name: Ensure urls.txt
        run: |
          if [ ! -s urls.txt ]; then
            cat > urls.txt <<'EOF'
https://ricette.giallozafferano.it/Gnocchi-alla-sorrentina.html
https://ricette.giallozafferano.it/Pollo-alla-cacciatora.html
https://ricette.giallozafferano.it/Lasagne-alla-Bolognese.html
https://ricette.giallozafferano.it/Tiramisu.html
https://ricette.giallozafferano.it/Pesto-alla-genovese.html
https://ricette.giallozafferano.it/Minestrone-di-verdure.html
EOF
          fi
          echo "Prime 5 URL:"
          head -n 5 urls.txt || true
          echo "Totale URL:"
          wc -l urls.txt

      - name: Echo
        run: echo "OK"
