name: Importa ricette (STEP 1 - skeleton)

on:
  workflow_dispatch: {}   # mostra il pulsante "Run workflow" su questo workflow

permissions:
  contents: read

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Sanity snapshot (non fallire)
        shell: bash
        run: |
          set +e
          echo "Node version:"; node -v
          echo "PWD:"; pwd
          echo "---- tree livello 2 ----"
          find . -maxdepth 2 -type f | sort | sed 's|^\./||' | head -n 400
          echo "---- esistenza file chiave ----"
          ls -lah package.json 2>/dev/null || echo "package.json NON presente"
          ls -lah package-lock.json 2>/dev/null || echo "package-lock.json NON presente"
          ls -lah script 2>/dev/null || echo "cartella script NON presente"
          ls -lah script/*.mjs 2>/dev/null || echo "nessun .mjs trovato in script/"
          ls -lah urls.txt 2>/dev/null || echo "urls.txt NON presente"
          if [ -f urls.txt ]; then echo "Righe urls.txt:"; wc -l urls.txt; fi
          echo "---- fine snapshot ----"

      - name: Carica snapshot come artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: snapshot-step1
          path: |
            urls.txt
            script/**
            package.json
            package-lock.json
          if-no-files-found: warn
