name: Sync recipes from Google Sheet

on:
  workflow_dispatch:
  schedule:
    - cron: '17 2 * * *'

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run sync
        env:
          SHEET_CSV_URL: ${{ vars.SHEET_CSV_URL }}
        run: node tools/sync-sheet.js

      - name: Commit and push changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add assets/json/recipes-it.json
            git commit -m "recipes: sync from sheet"
            git push
          else
            echo "No changes"
          fi
