name: Keep app.js in sync

on:
  workflow_dispatch:
  push:
    paths:
      - "script/app_v*.js"
      - ".github/workflows/sync-app.yml"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build app.js from latest app_v*
        run: |
          latest="$(ls -1 script | grep -E '^app_v[0-9]+' | sort -V | tail -n1)"
          echo "Latest file: $latest"
          mkdir -p script/app
          cp "script/$latest" "script/app/app.js"

      - name: Commit and push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            latest="$(ls -1 script | grep -E '^app_v[0-9]+' | sort -V | tail -n1)"
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add script/app/app.js
            git commit -m "chore: sync app.js from ${latest}"
            git push
          else
            echo "No changes"
          fi
